### ISSUE TITLE
does't show up in addons tab

### ISSUE THREAD

**Issue by TemmieDola** [Ruuubickk/NotEditingBasisShapekey#1]
I'm on blender version 3.3.5.
Addon works, but you need to install either py file, or manually go to the folder with addons and pull the py file in the folder above "3.3\scripts\addons" istead of "3.3\scripts\addons\NotEditingBasisShapekey-main"

**Comment by TemmieDola** [comment]
Tried searching by word shape and by folder name
![изображение](https://user-images.githubusercontent.com/93981726/229641564-67da8439-976e-41c2-bccd-f275c2368944.png)
![изображение](https://user-images.githubusercontent.com/93981726/229641521-f76e75d6-fff6-4faf-8462-28bca076e70c.png)
After installing the py file separately
![изображение](https://user-images.githubusercontent.com/93981726/229641695-14776bfd-7d54-455d-916a-c46118916edd.png)

**Comment by Ruuubickk** [comment]
> I'm on blender version 3.3.5. Addon works, but you need to install either py file, or manually go to the folder with addons and pull the py file in the folder above "3.3\scripts\addons" istead of "3.3\scripts\addons\NotEditingBasisShapekey-main"

Yeah this seems like an odd Blender quirk, a friend is having the same issue and I'm not sure what causes it...
I will update the install instructions in case other people run into the issue, thank you!
